sudo: false
language: ruby
rvm:
- 2.5.1
before_install:
  - gem install bundler
services:
- postgresql
before_script:
- psql -c 'create database lusiadas_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: qvLYwhTiiIUn8deQkaRdb6Cc7IILFSpdGj0PoIz/p1JeFw0SGxLuTtpv5YFD7cJJmYZIBjajarC2M+A/WsM7kydyZcEj9k8EOuzjIlFBoMbHy0pS2Mk1uQBmdUWaziSaik2AafQ6SnU69CqwK2WAtJQtsXCcGNYgvS/b9HnS7/vrrt/hXsd1Y2kTaTI20sIqOOKMxn0obNdRpQ/j5nnR9zmpghcovCOIbYXnRmz/Qr14MY2c165TmOrZ795QZGTAyDYmTmaQ0774ndOMvV8ZFWw5tC34o2QsHMhSmze1tU8JT+l+3ILwbeGx5ZcdBsIXa5K6iAESHI0yX01WKK/MGxhMzlARux5ChOoSKr7G6lLpT3VUjturYw3dzae9wEyYKmlUKDELErYSzyFuCp/BRATij0SfFwAeOAhK0fdPVvhKTZRbMGmleIvq1U1bNWVFDqSFG0pFtO6A+IMmHBIXzQPIVsY6vnWUtx6bEJUVtmQJ6acKB0GXJriL/BXJc55KsoHcVlD6a7tgiH1LFiu1+6dpedRHibsx29gb7AjQtDjzhkKD9wYGmooeV0g6T03eUKoeF6QYF/sCEnplakIUaxi7hj7T72BxOj0u2UW6273kYNkeB9thSrTqo2wU02YSWwH/ZOkwuxJ2m0akyRzTRDpfP4J0qcoNmFKM7S5WY0Y=
  app:
    master: pure-springs-67836
  run: "rails db:migrate"
