sudo: false
language: ruby
rvm:
- 2.6.2
before_install:
- gem install bundler
services:
- postgresql
before_script:
- psql -c 'create database lusiadas_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: r3jetRDU+wKXWToKuWGSwEqTWm60kmu/53Ism5J0B2l8IZALXM/21bUVOWeNu124wXCPKwZI44HHbWdPU/5eioC8aenLMYIbZPaaYAoYb+fngK5TdEA5HRPjlIrMY02Fs03RQvDgM5VFRI949Jxhc9Pzr1jq/Y4jbgFD5eDY5aO7qevPgLc3e35dR6EIMDi0YXKGJpr8H7aE0HX55qbDL/+StT87C/pHP+CGkG4T0FG1ltXLqvxrELxouLQTjkq1cETLpUE3+JqiPDHVJDu7Vdh0CBzNRx/5h4PHxWyiZQebpx+2pvVh3KAkVnAE7B3Jv83wTMQtDDZLRnoohS+AHLC2E8rf/6gWQlgaFS8snZAlzr3eYZBqSYihaN4s/U9ddV6dyqYUyKY/qwVqAoB6KxwACOIEOTK3yYxu29LgMcSLpz/qQAfWS+iQmgPERODL/n+pxAGRoH09IQDqxVNqfmgWAfWANA8S6RHqavM4w+3gF0hapDlO535d5a208GWFgHf4u+9VJB3dL0b/d05gE/E84xPVwxWI/9M4noI8Stwwz2kKcOpWOptoVU9r7Z8cLKPy1GFydDmIAYYsvz3T3NADmfREOdCqBXztRAw/xWMsJvw1CCay4PT8bUThfagqd3Z89FDCff5soVDkhR8POV1dY9xAvRQacZ8MLKySk9E=
  app:
    master: pure-springs-67836
  run: rails db:migrate
