sudo: false
language: ruby
rvm:
- 2.6.5
before_install:
- gem install bundler
services:
- postgresql
before_script:
- psql -c 'create database lusiadas_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: qn6NlBxm9JfF9OoLSmmGHPYjLuUoSucIBJctAlDskYuZc48ydnEVNvRvsPM+d9M89NgQdBMxWnMzyOkIfBNQRTDtqri9TrexG1gY7L+7H0RdDVgsmbDqZcGEbJtt1BofnjY/9oAa9PI5hV6OP4uCprhnu0600lGztp9kA7FFII1hehwaxISzuIdQIR5sGetRTIZGrzr7Dzgg6XeQz5lfj1zDbgGNEvY6EqJTNUFWhpZt7d4ZJjSnHkwdA+rNasWNkco+EsHPy/cgTE65WcJvppFOloXRqtJFZQc6+4iVrMRMCN4HvCwdHGCJy7YRggkZoMF54qwrpNqVu4tvJaKEPb2Yq6cVoPfL8CBWhw+3t1lrPJ0+utIHf1U08ZeTN08W1Nvj2ls1KJqKJzcvHJo1J/rNbbA+/cgw3dWxbG/nKP7r9X51nr09aQ3AWkMKG/LacjmJ+G9Q+uMdk2QA9b9eTGKp/1Dgo6eUtuIuB0OgghcQya8Lw/jMrE9wEjis4vwwacAW7oGfq3SYZ6WHpkVXeVcsAIym+NA598EOtK0kqAd4Frm0HtWNHXkmEwTZc3Qi9I/bv73WbvjmcLMT4r2wMX2R1avyOlOhJrD6kLTBly536JBz0HxzT4+yNfbPowXaQl9F44YnqnwMvUQZQxH/he2+o3YiG+KSNMTgUH+jGDs=
  app:
    master: pure-springs-67836
  run: rails db:migrate
